---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/weapons
  label: Weapons
  create: documents
  match: "**.md"
  new_doc_ext: md
  templates:
  - primordial-jade-winged-spear
upload_dir: ".netlify/large-media"
public_path: https://teyvat.venipa.net/images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn generate
